CREATE TABLE "approved_submissions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"approval_id" integer NOT NULL UNIQUE REFERENCES "project_approvals"("id") ON DELETE CASCADE,
	"project_id" integer NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,
	"user_id" uuid REFERENCES "users"("id") ON DELETE SET NULL,
	"author_name" text,
	"author_hca_id" text,
	"author_email" text,
	"author_street_address" text,
	"author_address_line_2" text,
	"author_locality" text,
	"author_region" text,
	"author_postal_code" text,
	"author_country" text,
	"project_name" text NOT NULL,
	"project_description" text,
	"project_repo_url" text,
	"project_demo_url" text,
	"project_screenshot_url" text,
	"project_ai_declaration" text,
	"hackatime_project" text,
	"submitted_seconds" integer NOT NULL,
	"approved_seconds" integer NOT NULL,
	"public_message" text,
	"submitted_at" timestamp with time zone NOT NULL,
	"approved_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
INSERT INTO "approved_submissions" (
	"approval_id", "project_id", "user_id",
	"author_name", "author_hca_id", "author_email",
	"author_street_address", "author_address_line_2", "author_locality",
	"author_region", "author_postal_code", "author_country",
	"project_name", "project_description", "project_repo_url",
	"project_demo_url", "project_screenshot_url", "project_ai_declaration",
	"hackatime_project",
	"submitted_seconds", "approved_seconds", "public_message",
	"submitted_at", "approved_at"
)
SELECT
	pa."id", pa."project_id", p."user_id",
	u."name", u."hca_id", u."email",
	u."street_address", u."address_line_2", u."locality",
	u."region", u."postal_code", u."country",
	p."name", p."description", p."repo_url",
	p."demo_url", p."screenshot_url", p."ai_declaration",
	p."hackatime_project",
	pa."submitted_seconds", COALESCE(pa."approved_seconds", 0), pa."public_message",
	pa."submitted_at", COALESCE(pa."reviewed_at", pa."submitted_at")
FROM "project_approvals" pa
JOIN "projects" p ON p."id" = pa."project_id"
JOIN "users" u ON u."id" = p."user_id"
WHERE pa."status" = 'approved';
