CREATE TABLE "grants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "grants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"approval_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"user_id" uuid,
	"submission_type" text NOT NULL,
	"payout_target" text NOT NULL,
	"workshop_id" integer,
	"amount_cents" integer DEFAULT 500 NOT NULL,
	"currency" text DEFAULT 'USD' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"recipient_name" text,
	"recipient_email" text,
	"recipient_country" text,
	"sent_by_id" uuid,
	"sent_at" timestamp with time zone,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "grants_approval_id_unique" UNIQUE("approval_id")
);
--> statement-breakpoint
ALTER TABLE "project_approvals" ALTER COLUMN "submitted_seconds" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "project_approvals" ADD COLUMN IF NOT EXISTS "submission_type" text;--> statement-breakpoint
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "submission_type" text;--> statement-breakpoint
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "workshop_id" integer;--> statement-breakpoint
-- NOTE: fraud_check (0028) and ysws_check_result (0027) were applied by earlier
-- hand-written migrations whose drizzle snapshots were never committed, so the
-- generator re-emitted them here. They are intentionally omitted to keep this
-- migration safe to apply on a DB that already ran 0027/0028.
ALTER TABLE "grants" ADD CONSTRAINT "grants_approval_id_project_approvals_id_fk" FOREIGN KEY ("approval_id") REFERENCES "public"."project_approvals"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grants" ADD CONSTRAINT "grants_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grants" ADD CONSTRAINT "grants_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grants" ADD CONSTRAINT "grants_sent_by_id_users_id_fk" FOREIGN KEY ("sent_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;