import { redirect, error, fail } from '@sveltejs/kit';
import { env } from '$env/dynamic/private';
import { dev } from '$app/environment';
import { db } from '$lib/server/db';
import {
	projects,
	users,
	projectEvents,
	projectApprovals,
	projectExploreSnapshots,
	approvedSubmissions,
	grants
} from '$lib/server/db/schema';
import { eq, and, ne, asc, desc, count, notExists, gt, sql } from 'drizzle-orm';
import { sendSlackDM, inviteToChannel } from '$lib/server/slack';
import { uploadImageBlob } from '$lib/server/cdn';
import { createAirtableApprovalRecord } from '$lib/server/airtable';
import { decryptToken, encryptionKey } from '$lib/server/session';
import {
	decideEligibility,
	isEligibleDecision,
	eligibilityMessage,
	calculateAge,
	type CheckResult
} from '$lib/server/eligibility';
import { checkYswsStatus } from '$lib/server/verification';
import { isStaging } from '$lib/server/staging';
import { getMembership } from '$lib/server/workshops';
import { getOrSeedFiles } from '$lib/server/editor';
import { publishSite } from '$lib/server/github';

const HACKATIME_BASE_URL = 'https://hackatime.hackclub.com';

/**
 * Normalize a user-supplied URL, allowing only http(s) schemes. Returns the
 * canonical href, or null for empty/invalid input or any other scheme. This is
 * the authoritative gate: the demo/repo URLs are later rendered as <a href>,
 * and Svelte does NOT strip dangerous schemes, so a stored `javascript:` URL
 * would be a stored XSS against reviewers and the public explore page. The
 * client-side prefixing in +page.svelte is convenience only and bypassable.
 */
function cleanUrl(raw: FormDataEntryValue | null): string | null {
	const v = (raw as string | null)?.trim();
	if (!v) return null;
	let u: URL;
	try {
		u = new URL(v);
	} catch {
		return null;
	}
	return u.protocol === 'http:' || u.protocol === 'https:' ? u.href : null;
}

// Channel reviewers watch to pick up new submissions. Overridable via env.
const REVIEW_CHANNEL_ID = env.SLACK_REVIEW_CHANNEL_ID || 'C0BBHACUXE1';

// Boba Drops tracks. Individual submissions pay cash to the teen and are US-only;
// workshop submissions route the grant to the club leader and are worldwide.
const SUBMISSION_TYPES = ['individual', 'workshop'] as const;
type SubmissionType = (typeof SUBMISSION_TYPES)[number];

function isSubmissionType(v: unknown): v is SubmissionType {
	return typeof v === 'string' && (SUBMISSION_TYPES as readonly string[]).includes(v);
}

// Whether a stored country value counts as the United States. Accepts the common
// spellings/codes; case- and punctuation-insensitive.
function isUnitedStates(country: string | null | undefined): boolean {
	if (!country) return false;
	const c = country.trim().toLowerCase().replace(/\./g, '');
	return [
		'us',
		'usa',
		'united states',
		'united states of america',
		'u s a',
		'u s'
	].includes(c);
}

// Autogenerated, internal-only comments posted when an admin toggles a project's
// fraud-check flag. Authors never see these (the actions are stripped from the
// visible-events payload for non-reviewers).
const FRAUD_CHECK_MESSAGE =
	'This project is currently being checked by the Fraud Squad - do not review';
const FRAUD_CHECK_CLEARED_MESSAGE =
	'Fraud check cleared by the Fraud Squad - this project can be reviewed again';

// Event actions that are reviewer/admin-only and must never reach the author.
const INTERNAL_ONLY_EVENT_ACTIONS = ['soft_approved', 'fraud_check', 'fraud_check_cleared'];

async function getDbUser(hcaId: string) {
	const [row] = await db.select().from(users).where(eq(users.hcaId, hcaId)).limit(1);
	return row ?? null;
}

/**
 * Post to the reviewer channel when a project is submitted or reshipped, so
 * reviewers know there's new work in the queue. Best-effort: never throws, and
 * is skipped on staging so test instances don't spam the real channel.
 */
async function notifyReviewChannel(opts: {
	origin: string;
	projectId: number;
	projectName: string;
	submitterSlackId: string | null;
	submitterName: string | null;
	submittedSeconds: number | null;
	submissionType?: string | null;
	isReship: boolean;
	repoUrl?: string | null;
	demoUrl?: string | null;
}) {
	if (isStaging()) return;
	try {
		const reviewUrl = `${opts.origin}/projects/${opts.projectId}`;
		const who = opts.submitterSlackId
			? `<@${opts.submitterSlackId}>`
			: opts.submitterName || 'Someone';
		const verb = opts.isReship ? 'reshipped' : 'shipped';
		const track = opts.submissionType ? ` _(${opts.submissionType})_` : '';
		const lines = [`:tea: *${who}* ${verb} *${opts.projectName}*${track}`];
		if (opts.repoUrl) lines.push(`• Repo: ${opts.repoUrl}`);
		if (opts.demoUrl) lines.push(`• Site: ${opts.demoUrl}`);
		lines.push(`<${reviewUrl}|Review on the dashboard>`);
		await sendSlackDM(REVIEW_CHANNEL_ID, lines.join('\n'));
	} catch (e) {
		console.error('failed to post submission notification to review channel', e);
	}
}

async function getHackatimeSeconds(
	dbUser: typeof users.$inferSelect,
	projectNames: string[]
): Promise<number> {
	if (!projectNames.length) return 0;
	if (!dbUser.hackatimeTokenCt || !dbUser.hackatimeTokenIv || !dbUser.hackatimeTokenTag) return 0;

	const encKey = encryptionKey();
	const accessToken = decryptToken(
		dbUser.hackatimeTokenCt,
		dbUser.hackatimeTokenIv,
		dbUser.hackatimeTokenTag,
		encKey
	);

	const res = await fetch(`${HACKATIME_BASE_URL}/api/v1/authenticated/projects`, {
		headers: { Authorization: `Bearer ${accessToken}` }
	});
	if (!res.ok) return 0;

	const data = await res.json();
	const raw: any[] = Array.isArray(data) ? data : (data.data ?? data.projects ?? []);
	const nameSet = new Set(projectNames);
	return raw
		.filter((p: any) => nameSet.has(String(p.name ?? '')))
		.reduce((sum: number, p: any) => sum + Number(p.total_seconds ?? p.totalSeconds ?? 0), 0);
}

async function getLatestApproval(projectId: number) {
	const [row] = await db
		.select()
		.from(projectApprovals)
		.where(eq(projectApprovals.projectId, projectId))
		.orderBy(desc(projectApprovals.submittedAt))
		.limit(1);
	return row ?? null;
}

export async function load({ locals, params }) {
	if (!locals.user) redirect(302, '/login');

	const id = parseInt(params.id, 10);
	if (isNaN(id)) error(404, 'project not found');

	const dbUser = await getDbUser(locals.user.sub);
	if (!dbUser) redirect(302, '/login');

	const [project] = await db.select().from(projects).where(eq(projects.id, id)).limit(1);

	if (!project || (!locals.isReviewer && project.userId !== dbUser.id)) {
		redirect(302, '/projects?error=not_found');
	}

	const approvals = await db
		.select({
			id: projectApprovals.id,
			status: projectApprovals.status,
			submittedSeconds: projectApprovals.submittedSeconds,
			approvedSeconds: projectApprovals.approvedSeconds,
			publicMessage: projectApprovals.publicMessage,
			internalNote: projectApprovals.internalNote,
			submittedAt: projectApprovals.submittedAt,
			reviewedAt: projectApprovals.reviewedAt,
			reviewerName: users.name,
			reviewerNickname: users.nickname,
			reviewerAvatar: users.slackAvatarUrl
		})
		.from(projectApprovals)
		.leftJoin(users, eq(projectApprovals.reviewerId, users.id))
		.where(eq(projectApprovals.projectId, id))
		.orderBy(asc(projectApprovals.submittedAt));

	// Legacy hours delta — Boba Drops no longer credits hours, but the field is kept
	// (always 0) so the returned shape stays stable for any UI still referencing it.
	const approvalsWithDelta = approvals.map((a) => ({ ...a, newSeconds: 0 }));

	// soft_approved is internal-only — non-reviewers/admins see it as still pending.
	// Relabel (rather than hide) the soft_approved approval so the author lands on the
	// pending view; hiding it would expose a stale approved/rejected status and wrongly
	// surface the reship/submit view while final confirmation is outstanding.
	const isInternal = locals.isReviewer || locals.isAdmin;
	const visibleApprovals = isInternal
		? approvalsWithDelta
		: approvalsWithDelta.map((a) => {
				if (a.status === 'soft_approved') {
					return {
						...a,
						status: 'pending',
						approvedSeconds: null,
						publicMessage: null,
						internalNote: null,
						reviewedAt: null,
						reviewerName: null,
						reviewerNickname: null,
						reviewerAvatar: null
					};
				}
				return { ...a, internalNote: null };
			});

	const latestApproval =
		visibleApprovals.length > 0 ? visibleApprovals[visibleApprovals.length - 1] : null;
	const derivedStatus: string | null = latestApproval?.status ?? null;

	const events = await db
		.select({
			id: projectEvents.id,
			action: projectEvents.action,
			message: projectEvents.message,
			internalNote: projectEvents.internalNote,
			createdAt: projectEvents.createdAt,
			actorName: users.name,
			actorNickname: users.nickname,
			actorAvatar: users.slackAvatarUrl
		})
		.from(projectEvents)
		.innerJoin(users, eq(projectEvents.actorId, users.id))
		.where(eq(projectEvents.projectId, id))
		.orderBy(asc(projectEvents.createdAt));

	const linkedRows = await db
		.select({ hackatimeProject: projects.hackatimeProject })
		.from(projects)
		.where(and(ne(projects.id, id), eq(projects.userId, dbUser.id)));
	const linkedHackatimeProjects = linkedRows.flatMap((r) =>
		r.hackatimeProject
			? r.hackatimeProject
					.split(',')
					.map((s) => s.trim())
					.filter(Boolean)
			: []
	);

	const [projectOwnerRow] = await db
		.select({
			name: users.name,
			nickname: users.nickname,
			avatar: users.slackAvatarUrl,
			slackId: users.slackId,
			slackDisplayName: users.slackDisplayName,
			verificationStatus: users.verificationStatus,
			yswsEligible: users.yswsEligible,
			yswsCheckResult: users.yswsCheckResult,
			birthday: users.birthday
		})
		.from(users)
		.where(eq(users.id, project.userId))
		.limit(1);

	// Reviewer-only panel data: Slack handle, ID verification status, and the
	// current YSWS eligibility decision for the project's author. Only ever sent
	// to reviewers/admins so we don't leak it back to the owner's own view.
	const ownerReviewInfo =
		isInternal && projectOwnerRow
			? (() => {
					const result = (projectOwnerRow.yswsCheckResult as CheckResult | null) ?? null;
					const decision = decideEligibility(result, projectOwnerRow.birthday);
					return {
						slackId: projectOwnerRow.slackId,
						slackDisplayName: projectOwnerRow.slackDisplayName,
						verificationStatus: projectOwnerRow.verificationStatus,
						yswsCheckResult: result,
						yswsEligible: projectOwnerRow.yswsEligible,
						// age is admin-only; reviewers see eligibility but not the raw age
					age: locals.isAdmin ? calculateAge(projectOwnerRow.birthday) : null,
						eligibilityDecision: decision,
						eligible: isEligibleDecision(decision)
					};
				})()
			: null;

	const visibleEvents = isInternal
		? events
		: events
				.filter((e) => !INTERNAL_ONLY_EVENT_ACTIONS.includes(e.action))
				.map(({ internalNote: _n, ...rest }) => ({ ...rest, internalNote: null }));

	return {
		project,
		approvals: visibleApprovals,
		events: visibleEvents,
		latestApproval,
		derivedStatus,
		// Legacy field retained for back-compat with the project page; hours are gone.
		availableSeconds: 0,
		linkedHackatimeProjects,
		projectOwner: projectOwnerRow
			? {
					name: projectOwnerRow.name,
					nickname: projectOwnerRow.nickname,
					avatar: projectOwnerRow.avatar
				}
			: null,
		ownerReviewInfo,
		isReviewer: locals.isReviewer,
		isAdmin: locals.isAdmin,
		isOwnProject: project.userId === dbUser.id,
		githubConnected: !!locals.user.github_login
	};
}

export const actions = {
	// Push the site's files to the user's GitHub repo + enable Pages.
	publish: async ({ locals, params }) => {
		if (!locals.user) redirect(302, '/login');
		const id = parseInt(params.id, 10);
		if (isNaN(id)) error(404, 'project not found');

		const dbUser = await getDbUser(locals.user.sub);
		if (!dbUser) redirect(302, '/login');

		const [projectRow] = await db
			.select()
			.from(projects)
			.where(and(eq(projects.id, id), eq(projects.userId, dbUser.id)))
			.limit(1);
		if (!projectRow) return fail(404, { error: 'project not found' });

		const files = await getOrSeedFiles(id, projectRow.name);

		let result;
		try {
			result = await publishSite(dbUser, projectRow.name, files, projectRow.githubRepo);
		} catch (e) {
			return fail(400, { error: (e as Error).message });
		}

		await db
			.update(projects)
			.set({
				githubRepo: result.repoFullName,
				githubRepoUrl: result.repoUrl,
				repoUrl: result.repoUrl,
				demoUrl: result.pagesUrl,
				publishedAt: new Date(),
				updatedAt: new Date()
			})
			.where(and(eq(projects.id, id), eq(projects.userId, dbUser.id)));

		return { published: true, pagesUrl: result.pagesUrl };
	},

	save: async ({ request, locals, params }) => {
		if (!locals.user) redirect(302, '/login');

		const id = parseInt(params.id, 10);
		if (isNaN(id)) error(404, 'project not found');

		const dbUser = await getDbUser(locals.user.sub);
		if (!dbUser) redirect(302, '/login');

		let form: FormData;
		try {
			form = await request.formData();
		} catch {
			return fail(400, { error: 'invalid form submission' });
		}
		const name = (form.get('name') as string)?.trim();
		const description = (form.get('description') as string)?.trim() || null;
		const rawRepoUrl = (form.get('repo_url') as string)?.trim() || null;
		const rawDemoUrl = (form.get('demo_url') as string)?.trim() || null;
		const repoUrl = cleanUrl(form.get('repo_url'));
		const demoUrl = cleanUrl(form.get('demo_url'));
		const hackatimeProject = (form.get('hackatime_project') as string)?.trim() || null;
		const aiDeclaration = (form.get('ai_declaration') as string)?.trim() || null;

		if (!name) return fail(400, { error: 'project name is required' });
		if (rawRepoUrl && !repoUrl)
			return fail(400, { error: 'repo url must be a valid http(s) url' });
		if (rawDemoUrl && !demoUrl)
			return fail(400, { error: 'demo url must be a valid http(s) url' });

		const [ownedProject] = await db
			.select({ id: projects.id })
			.from(projects)
			.where(and(eq(projects.id, id), eq(projects.userId, dbUser.id)))
			.limit(1);

		if (!ownedProject) return fail(403, { error: 'project not found' });

		const rawKeepUrl = (form.get('screenshot_keep') as string)?.trim() || null;
		const keepUrl =
			rawKeepUrl?.startsWith('https://cdn.hackclub.com/') ? rawKeepUrl : null;
		let screenshotUrl: string | null = keepUrl;
		const file = form.get('screenshot1');
		if (file instanceof File && file.size > 0) {
			try {
				screenshotUrl = await uploadImageBlob(file, file.name);
			} catch (e) {
				return fail(400, { error: `screenshot upload failed: ${(e as Error).message}` });
			}
		}

		await db
			.update(projects)
			.set({
				name,
				description,
				screenshotUrl,
				repoUrl,
				demoUrl,
				hackatimeProject,
				aiDeclaration,
				updatedAt: new Date()
			})
			.where(and(eq(projects.id, id), eq(projects.userId, dbUser.id)));

		return { success: true };
	},

	submit: async ({ request, locals, params }) => {
		if (!locals.user) redirect(302, '/login');

		const id = parseInt(params.id, 10);
		if (isNaN(id)) error(404, 'project not found');

		const dbUser = await getDbUser(locals.user.sub);
		if (!dbUser) redirect(302, '/login');

		const [projectRow] = await db
			.select()
			.from(projects)
			.where(and(eq(projects.id, id), eq(projects.userId, dbUser.id)))
			.limit(1);

		if (!projectRow) return fail(400, { error: 'project not found' });

		const [{ total: approvalCount }] = await db
			.select({ total: count() })
			.from(projectApprovals)
			.where(eq(projectApprovals.projectId, id));

		if (approvalCount > 0)
			return fail(400, { error: 'project already submitted, use reship to submit new work' });

		const eligibility = decideEligibility(await checkYswsStatus(locals.user.sub), dbUser.birthday);
		if (!isEligibleDecision(eligibility))
			return fail(403, { error: eligibilityMessage(eligibility) });

		if (!dbUser.streetAddress || !dbUser.locality || !dbUser.country)
			return fail(400, {
				error: 'add your address in account settings before submitting'
			});

		const form = await request.formData();
		const name = (form.get('name') as string)?.trim();
		const description = (form.get('description') as string)?.trim() || null;
		const repoUrl = cleanUrl(form.get('repo_url'));
		const demoUrl = cleanUrl(form.get('demo_url'));
		const submissionTypeRaw = (form.get('submission_type') as string)?.trim();

		if (!name) return fail(400, { error: 'project name is required' });

		// Boba Drops: pick a track. Individuals get cash (US-only); workshops route
		// the grant to the club leader (worldwide). If the builder belongs to a
		// workshop, their track is forced to 'workshop' regardless of the form.
		const membership = await getMembership(dbUser.id);
		let submissionType: SubmissionType;
		let workshopId: number | null = null;
		if (membership) {
			submissionType = 'workshop';
			workshopId = membership.workshopId;
		} else {
			if (!isSubmissionType(submissionTypeRaw))
				return fail(400, { error: 'choose how you’re submitting: individually or with a workshop' });
			submissionType = submissionTypeRaw;
		}
		if (submissionType === 'individual' && !isUnitedStates(dbUser.country))
			return fail(400, {
				error:
					'individual cash submissions are US-only right now — join or run a workshop to take part from outside the US'
			});

		const rawKeepUrl = (form.get('screenshot_keep') as string)?.trim() || null;
		const keepUrl = rawKeepUrl?.startsWith('https://cdn.hackclub.com/') ? rawKeepUrl : null;
		let screenshotUrl: string | null = keepUrl;
		const file = form.get('screenshot1');
		if (file instanceof File && file.size > 0) {
			try {
				screenshotUrl = await uploadImageBlob(file, file.name);
			} catch (e) {
				return fail(400, { error: `screenshot upload failed: ${(e as Error).message}` });
			}
		}

		if (!description) return fail(400, { error: 'description is required before submitting' });
		if (!repoUrl) return fail(400, { error: 'your code repo (github) is required before submitting' });
		if (!demoUrl) return fail(400, { error: 'your live site url (github pages) is required before submitting' });
		if (!screenshotUrl) return fail(400, { error: 'screenshot is required before submitting' });

		const aiDeclaration = (form.get('ai_declaration') as string)?.trim() || null;
		const hackatimeProject = (form.get('hackatime_project') as string)?.trim() || null;
		// Hackatime is no longer required to submit; if the builder happens to have it
		// linked we still capture the time for context, otherwise it's simply null.
		const projectNames = (hackatimeProject ?? '')
			.split(',')
			.map((s) => s.trim())
			.filter(Boolean);
		const totalSeconds = projectNames.length
			? await getHackatimeSeconds(dbUser, projectNames)
			: null;

		await db
			.update(projects)
			.set({
				name,
				description,
				screenshotUrl,
				repoUrl,
				demoUrl,
				hackatimeProject,
				aiDeclaration,
				submissionType,
				workshopId,
				updatedAt: new Date()
			})
			.where(and(eq(projects.id, id), eq(projects.userId, dbUser.id)));

		await db.insert(projectApprovals).values({
			projectId: id,
			submittedById: dbUser.id,
			submittedSeconds: totalSeconds,
			submissionType,
			status: 'pending',
			aiDeclaration
		});

		await notifyReviewChannel({
			origin: new URL(request.url).origin,
			projectId: id,
			projectName: name,
			submitterSlackId: dbUser.slackId,
			submitterName: dbUser.name,
			submittedSeconds: totalSeconds,
			submissionType,
			isReship: false,
			repoUrl,
			demoUrl
		});

		return { success: true };
	},

	reship: async ({ request, locals, params }) => {
		if (!locals.user) redirect(302, '/login');

		const id = parseInt(params.id, 10);
		if (isNaN(id)) error(404, 'project not found');

		const dbUser = await getDbUser(locals.user.sub);
		if (!dbUser) redirect(302, '/login');

		const [projectRow] = await db
			.select()
			.from(projects)
			.where(and(eq(projects.id, id), eq(projects.userId, dbUser.id)))
			.limit(1);

		if (!projectRow) return fail(404, { error: 'project not found' });

		const latestApproval = await getLatestApproval(id);
		if (!latestApproval) return fail(400, { error: 'no prior submission found' });
		if (latestApproval.status === 'pending')
			return fail(400, { error: 'a review is already pending for this project' });
		if (latestApproval.status === 'approved')
			return fail(400, { error: 'this site is already approved' });

		const eligibility = decideEligibility(await checkYswsStatus(locals.user.sub), dbUser.birthday);
		if (!isEligibleDecision(eligibility))
			return fail(403, { error: eligibilityMessage(eligibility) });

		if (!dbUser.streetAddress || !dbUser.locality || !dbUser.country)
			return fail(400, {
				error: 'add your address in account settings before submitting'
			});

		// Carry the original track forward. Re-check the US gate for individuals in
		// case the builder's country changed since the first submission.
		const submissionType = projectRow.submissionType ?? latestApproval.submissionType ?? null;
		if (submissionType === 'individual' && !isUnitedStates(dbUser.country))
			return fail(400, {
				error:
					'individual cash submissions are US-only right now — join or run a workshop to take part from outside the US'
			});

		// Best-effort time capture only (Hackatime is optional now).
		const projectNames = (projectRow.hackatimeProject ?? '')
			.split(',')
			.map((s) => s.trim())
			.filter(Boolean);
		const currentSeconds = projectNames.length
			? await getHackatimeSeconds(dbUser, projectNames)
			: null;

		await db.insert(projectApprovals).values({
			projectId: id,
			submittedById: dbUser.id,
			submittedSeconds: currentSeconds,
			submissionType,
			status: 'pending',
			aiDeclaration: projectRow.aiDeclaration ?? null
		});

		await notifyReviewChannel({
			origin: new URL(request.url).origin,
			projectId: id,
			projectName: projectRow.name,
			submitterSlackId: dbUser.slackId,
			submitterName: dbUser.name,
			submittedSeconds: currentSeconds,
			submissionType,
			isReship: true,
			repoUrl: projectRow.repoUrl,
			demoUrl: projectRow.demoUrl
		});

		return { success: true };
	},

	delete: async ({ locals, params }) => {
		if (!locals.user) redirect(302, '/login');

		const id = parseInt(params.id, 10);
		if (isNaN(id)) error(404, 'project not found');

		const dbUser = await getDbUser(locals.user.sub);
		if (!dbUser) redirect(302, '/login');

		const [ownedProject] = await db
			.select({ id: projects.id })
			.from(projects)
			.where(and(eq(projects.id, id), eq(projects.userId, dbUser.id)))
			.limit(1);

		if (!ownedProject) return fail(404, { error: 'project not found' });

		const [{ total: approvalCount }] = await db
			.select({ total: count() })
			.from(projectApprovals)
			.where(eq(projectApprovals.projectId, id));

		if (approvalCount > 0)
			return fail(403, { error: 'cannot delete a submitted or approved project' });

		await db.delete(projects).where(eq(projects.id, id));

		redirect(302, '/projects');
	},

	reject: async ({ request, locals, params }) => {
		if (!locals.isReviewer || !locals.user) return fail(403, { error: 'forbidden' });

		const id = parseInt(params.id, 10);
		if (isNaN(id)) error(404, 'project not found');

		const reviewerDbUser = await getDbUser(locals.user.sub);
		if (!reviewerDbUser) return fail(403, { error: 'forbidden' });

		const form = await request.formData();
		const message = (form.get('message') as string)?.trim() || null;
		const internalNote = (form.get('internal_note') as string)?.trim() || null;

		if (!message) return fail(400, { error: 'message to author is required' });
		if (!internalNote) return fail(400, { error: 'internal note is required' });

		const latestApproval = await getLatestApproval(id);
		if (!latestApproval || (latestApproval.status !== 'pending' && latestApproval.status !== 'soft_approved')) {
			return fail(400, { error: 'can only reject pending or soft approved projects' });
		}

		await db
			.update(projectApprovals)
			.set({
				status: 'rejected',
				reviewerId: reviewerDbUser.id,
				publicMessage: message,
				internalNote,
				reviewedAt: new Date()
			})
			.where(eq(projectApprovals.id, latestApproval.id));

		const [rejectedProject] = await db
			.select({ name: projects.name, userId: projects.userId })
			.from(projects)
			.where(eq(projects.id, id))
			.limit(1);

		if (rejectedProject) {
			const [ownerUser] = await db
				.select({ slackId: users.slackId })
				.from(users)
				.where(eq(users.id, rejectedProject.userId))
				.limit(1);

			if (ownerUser?.slackId) {
				const dashboardUrl = `${new URL(request.url).origin}/projects/${id}`;
				const quote = message
					? `\n${message
							.split('\n')
							.map((l) => `>${l}`)
							.join('\n')}\n`
					: '\n';
				await sendSlackDM(
					ownerUser.slackId,
					`Your project *${rejectedProject.name}* was rejected.${quote}<${dashboardUrl}|See more on the dashboard>`
				);
			}
		}

		return { success: true };
	},

	softApprove: async ({ request, locals, params }) => {
		if ((!locals.isReviewer && !locals.isAdmin) || !locals.user)
			return fail(403, { error: 'forbidden' });

		const id = parseInt(params.id, 10);
		if (isNaN(id)) error(404, 'project not found');

		const reviewerDbUser = await getDbUser(locals.user.sub);
		if (!reviewerDbUser) return fail(403, { error: 'forbidden' });

		const latestApproval = await getLatestApproval(id);
		if (!latestApproval || latestApproval.status !== 'pending') {
			return fail(400, { error: 'can only soft-approve pending projects' });
		}

		const form = await request.formData();
		const message = (form.get('message') as string)?.trim() || null;
		const internalNote = (form.get('internal_note') as string)?.trim() || null;

		if (!message) return fail(400, { error: 'message to author is required' });
		if (!internalNote) return fail(400, { error: 'internal note is required' });

		// Boba Drops approval is binary — a site passes or it doesn't. No hours to set.
		await db
			.update(projectApprovals)
			.set({
				status: 'soft_approved',
				reviewerId: reviewerDbUser.id,
				publicMessage: message,
				internalNote,
				reviewedAt: new Date()
			})
			.where(eq(projectApprovals.id, latestApproval.id));

		return { success: true };
	},

	approve: async ({ request, locals, params }) => {
		if (!locals.isAdmin || !locals.user) return fail(403, { error: 'forbidden' });

		const id = parseInt(params.id, 10);
		if (isNaN(id)) error(404, 'project not found');

		const reviewerDbUser = await getDbUser(locals.user.sub);
		if (!reviewerDbUser) return fail(403, { error: 'forbidden' });

		const latestApproval = await getLatestApproval(id);
		if (!latestApproval || (latestApproval.status !== 'pending' && latestApproval.status !== 'soft_approved')) {
			return fail(400, { error: 'can only approve pending or soft-approved projects' });
		}

		let message: string | null;
		let internalNote: string | null;

		if (latestApproval.status === 'soft_approved') {
			// Confirm the existing soft approval — reuse its message/note.
			message = latestApproval.publicMessage;
			internalNote = latestApproval.internalNote;
		} else {
			// Full approval straight from pending — require the message + note.
			const form = await request.formData();
			message = (form.get('message') as string)?.trim() || null;
			internalNote = (form.get('internal_note') as string)?.trim() || null;

			if (!message) return fail(400, { error: 'message to author is required' });
			if (!internalNote) return fail(400, { error: 'internal note is required' });
		}

		await db
			.update(projectApprovals)
			.set({
				status: 'approved',
				reviewerId: reviewerDbUser.id,
				publicMessage: message,
				internalNote,
				reviewedAt: new Date()
			})
			.where(eq(projectApprovals.id, latestApproval.id));

		const [projectData] = await db.select().from(projects).where(eq(projects.id, id)).limit(1);

		if (projectData) {
			const [authorUser] = await db
				.select()
				.from(users)
				.where(eq(users.id, projectData.userId))
				.limit(1);

			// Track decides who the $5 goes to: individuals get cash mailed to the
			// teen; workshop builders' grants route to the club leader.
			const submissionType =
				latestApproval.submissionType ?? projectData.submissionType ?? 'individual';
			const payoutTarget = submissionType === 'workshop' ? 'leader' : 'teen';

			await db.insert(approvedSubmissions).values({
				approvalId: latestApproval.id,
				projectId: id,
				userId: projectData.userId,
				authorName: authorUser?.name ?? null,
				authorHcaId: authorUser?.hcaId ?? null,
				authorEmail: authorUser?.email ?? null,
				authorStreetAddress: authorUser?.streetAddress ?? null,
				authorAddressLine2: authorUser?.addressLine2 ?? null,
				authorLocality: authorUser?.locality ?? null,
				authorRegion: authorUser?.region ?? null,
				authorPostalCode: authorUser?.postalCode ?? null,
				authorCountry: authorUser?.country ?? null,
				authorBirthday: authorUser?.birthday ?? null,
				projectName: projectData.name,
				projectDescription: projectData.description,
				projectRepoUrl: projectData.repoUrl,
				projectDemoUrl: projectData.demoUrl,
				projectScreenshotUrl: projectData.screenshotUrl,
				projectAiDeclaration: projectData.aiDeclaration,
				hackatimeProject: projectData.hackatimeProject,
				submittedSeconds: latestApproval.submittedSeconds ?? 0,
				approvedSeconds: latestApproval.submittedSeconds ?? 0,
				publicMessage: message,
				internalNote,
				submittedAt: latestApproval.submittedAt,
				approvedAt: new Date()
			});

			// Create the $5 grant in 'pending' state. An admin marks it 'sent' once
			// it's been paid out (cash to the teen, or grant to the club leader).
			await db.insert(grants).values({
				approvalId: latestApproval.id,
				projectId: id,
				userId: projectData.userId,
				submissionType,
				payoutTarget,
				workshopId: projectData.workshopId ?? null,
				recipientName: authorUser?.name ?? null,
				recipientEmail: authorUser?.email ?? null,
				recipientCountry: authorUser?.country ?? null
			});

			// Best-effort: the grant row in our DB is the source of truth, so a
			// misconfigured/erroring Airtable must NOT fail the approval. Log and move on.
			try {
				await createAirtableApprovalRecord({
					repoUrl: projectData.repoUrl,
					demoUrl: projectData.demoUrl,
					authorName: authorUser?.name ?? null,
					authorEmail: authorUser?.email ?? null,
					screenshotUrl: projectData.screenshotUrl,
					description: projectData.description,
					authorStreetAddress: authorUser?.streetAddress ?? null,
					authorAddressLine2: authorUser?.addressLine2 ?? null,
					authorLocality: authorUser?.locality ?? null,
					authorRegion: authorUser?.region ?? null,
					authorCountry: authorUser?.country ?? null,
					authorPostalCode: authorUser?.postalCode ?? null,
					authorBirthday: authorUser?.birthday ?? null,
					submissionType,
					payoutTarget,
					internalNote
				});
			} catch (e) {
				console.error('[airtable] failed to mirror approval (grant still recorded in DB):', e);
			}

			await db
				.insert(projectExploreSnapshots)
				.values({
					projectId: id,
					name: projectData.name,
					description: projectData.description,
					screenshotUrl: projectData.screenshotUrl,
					demoUrl: projectData.demoUrl,
					totalApprovedSeconds: 0,
					updatedAt: new Date()
				})
				.onConflictDoUpdate({
					target: projectExploreSnapshots.projectId,
					set: {
						name: projectData.name,
						description: projectData.description,
						screenshotUrl: projectData.screenshotUrl,
						demoUrl: projectData.demoUrl,
						updatedAt: new Date()
					}
				});

			if (authorUser?.slackId) {
				const dashboardUrl = `${new URL(request.url).origin}/projects/${id}`;
				const quote = message
					? `\n${message
							.split('\n')
							.map((l) => `>${l}`)
							.join('\n')}\n`
					: '\n';
				const reward =
					payoutTarget === 'leader'
						? 'Your $5 boba grant is on its way to your club leader'
						: 'Your $5 for boba is on its way';
				await sendSlackDM(
					authorUser.slackId,
					`Your site *${projectData.name}* was approved! 🧋 ${reward}.${quote}<${dashboardUrl}|See more on the dashboard>`
				);
				// add the author to the approved-builders Slack channel on a hard approval
				if (env.SLACK_APPROVED_CHANNEL_ID) {
					await inviteToChannel(authorUser.slackId, env.SLACK_APPROVED_CHANNEL_ID);
				}
			}
		}

		return { success: true };
	},

	comment: async ({ request, locals, params }) => {
		if (!locals.isReviewer || !locals.user) return fail(403, { error: 'forbidden' });

		const id = parseInt(params.id, 10);
		if (isNaN(id)) error(404, 'project not found');

		const reviewerDbUser = await getDbUser(locals.user.sub);
		if (!reviewerDbUser) return fail(403, { error: 'forbidden' });

		const form = await request.formData();
		const message = (form.get('message') as string)?.trim() || null;
		const internalNote = (form.get('internal_note') as string)?.trim() || null;

		if (!message && !internalNote)
			return fail(400, { error: 'comment must have a message or internal note' });

		const [projectRow] = await db
			.select({ id: projects.id })
			.from(projects)
			.where(eq(projects.id, id))
			.limit(1);

		if (!projectRow) return fail(404, { error: 'project not found' });

		await db.insert(projectEvents).values({
			projectId: id,
			actorId: reviewerDbUser.id,
			action: 'comment',
			message,
			internalNote
		});

		return { success: true };
	},

	fraudCheck: async ({ locals, params }) => {
		if (!locals.isAdmin || !locals.user) return fail(403, { error: 'forbidden' });

		const id = parseInt(params.id, 10);
		if (isNaN(id)) error(404, 'project not found');

		const adminDbUser = await getDbUser(locals.user.sub);
		if (!adminDbUser) return fail(403, { error: 'forbidden' });

		const [projectRow] = await db
			.select({ id: projects.id, fraudCheck: projects.fraudCheck })
			.from(projects)
			.where(eq(projects.id, id))
			.limit(1);

		if (!projectRow) return fail(404, { error: 'project not found' });
		// Already flagged — nothing to do (avoids a duplicate autogenerated comment).
		if (projectRow.fraudCheck) return { success: true };

		await db.update(projects).set({ fraudCheck: true }).where(eq(projects.id, id));

		await db.insert(projectEvents).values({
			projectId: id,
			actorId: adminDbUser.id,
			action: 'fraud_check',
			message: FRAUD_CHECK_MESSAGE
		});

		return { success: true };
	},

	clearFraudCheck: async ({ locals, params }) => {
		if (!locals.isAdmin || !locals.user) return fail(403, { error: 'forbidden' });

		const id = parseInt(params.id, 10);
		if (isNaN(id)) error(404, 'project not found');

		const adminDbUser = await getDbUser(locals.user.sub);
		if (!adminDbUser) return fail(403, { error: 'forbidden' });

		const [projectRow] = await db
			.select({ id: projects.id, fraudCheck: projects.fraudCheck })
			.from(projects)
			.where(eq(projects.id, id))
			.limit(1);

		if (!projectRow) return fail(404, { error: 'project not found' });
		// Not flagged — nothing to clear.
		if (!projectRow.fraudCheck) return { success: true };

		await db.update(projects).set({ fraudCheck: false }).where(eq(projects.id, id));

		await db.insert(projectEvents).values({
			projectId: id,
			actorId: adminDbUser.id,
			action: 'fraud_check_cleared',
			message: FRAUD_CHECK_CLEARED_MESSAGE
		});

		return { success: true };
	}
};
